In [13]:
import torch

# Create two random tensors
RANDOM_SEED=42 # 
torch.manual_seed(seed=RANDOM_SEED)  # This resets after every call to rand
random_tensor_A = torch.rand(3, 4)
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B


Tensor A:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor B:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [14]:
# Make permanent
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)
print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
import torch
torch.cuda.is_available()
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [16]:
if device == "cuda":
    print(f"Using {torch.cuda.device_count()} GPU")


Using 1 GPU


In [17]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

if device == "cuda":
    # Move tensor to GPU (if available)
    tensor_on_gpu = tensor.to(device)
    print(tensor_on_gpu, tensor.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cpu


In [18]:
# NumPy doesn't used the GPU
try:
    tensor_on_gpu.numpy()
except Exception as e:
    print("NumPy doesn't use the GPU")

# Move tensor back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

NumPy doesn't use the GPU


array([1, 2, 3], dtype=int64)